name: Continuous Integration Tests

on:
  push:
    branches:
      - master 
      - release
  pull_request:
    branches:
      - master 
      - release
jobs:
  lint:
    strategy:
      fail-fast: false #ensure both tests run even if one fails
      matrix:
        os: [ubuntu-latest, windows-latest]   
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Backend Linting 
        run: ./gradlew lint --continue 
      - name: Install Frontend Dependencies
        run: npm ci 
      - name: Run Lint Checks 
        run: npm run lint 
  component-testing:
    strategy:
      fail-fast: false #ensure both tests run even if one fails
      matrix:
        os: [ubuntu-latest, windows-latest]   
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Backend Tests    
        run: |
          ./gradlew createConfigs componentTests 
          ./gradlew jacocoReport
      - name: Generate Types 
        run: ./gradlew generateTypes
      - name: Install Frontend Dependencies 
        run: npm ci 
      - name: Run Frontend Tests 
        run: npm run coverage 
      - name: Upload to Codecov 
        if: matrix.os == 'ubuntu-latest' #only upload to codecov on ubuntu VM 
        run: bash <(curl -s https://codecov.io/bash)
  E2E-testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false #ensure both tests run even if one fails
      matrix:
        browser: [firefox]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Update Property File 
        run: mv $GITHUB_WORKSPACE/src/e2e/resources/test.ci-$E2E_BROWSER.properties src/e2e/resources/test.properties
        env:
          E2E_BROWSER: ${{ matrix.browser }}
      - name: Create Config Files 
        run: ./gradlew createConfigs testClasses generateTypes 
      - name: Install Frontend Dependencies
        run: npm ci 
      - name: Build Frontend Bundle 
        run: npm run build -- --progress=false --serviceWorker=false 
      - name: Start App Engine 
        run: ./gradlew appengineStart 
      - name: Start Tests 
        run: xvfb-run --server-args="-screen 0 1024x768x24" ./gradlew e2eTests 
